apiVersion: v1
kind: ConfigMap
metadata:
  name: pokus-ewg-config
  labels:
    app: pokus-ewg
data:
  # Quarkus will look for application.properties in QUARKUS_CONFIG_LOCATIONS
  application.properties: |
    # Override/custom properties for k8s
    app.random=nr2
