apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pokus-ewg
  labels:
    app: pokus-ewg
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /kamiony
        pathType: Prefix
        backend:
          service:
            name: pokus-ewg
            port:
              number: 8080
      - path: /q
        pathType: Prefix
        backend:
          service:
            name: pokus-ewg
            port:
              number: 8080
